In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel(r"/content/Rawdata.xlsx")
df

     Name          Domain       Age   Location   Salary      Exp
0    Mike   Datascience#$  34 years     Mumbai   5^00#0       2+
1  Teddy^         Testing    45' yr  Bangalore  10%%000       <3
2   Uma#r  Dataanalyst^^#       NaN        NaN  1$5%000   4> yrs
3    Jane     Ana^^lytics       NaN   Hyderbad   2000^0      NaN
4  Uttam*      Statistics     67-yr        NaN   30000-  5+ year
5     Kim             NLP      55yr      Delhi  6000^$0      10+

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [ ]:
df.columns

Index(['Name', 'Domain', 'Age', 'Location', 'Salary', 'Exp'], dtype='object')

In [ ]:
df['Name'].replace(r'\W','$$$$$',regex = True)  #That's how this operation works

0          Mike
1    Teddy$$$$$
2     Uma$$$$$r
3          Jane
4    Uttam$$$$$
5           Kim
Name: Name, dtype: object

In [ ]:
df['Name']

0      Mike
1    Teddy^
2     Uma#r
3      Jane
4    Uttam*
5       Kim
Name: Name, dtype: object

In [ ]:
for i in df.columns:
  df[i] = df[i].replace('\W','',regex = True)

In [ ]:
df

    Name       Domain      Age   Location Salary    Exp
0   Mike  Datascience  34years     Mumbai   5000      2
1  Teddy      Testing     45yr  Bangalore  10000      3
2   Umar  Dataanalyst      NaN        NaN  15000   4yrs
3   Jane    Analytics      NaN   Hyderbad  20000    NaN
4  Uttam   Statistics     67yr        NaN  30000  5year
5    Kim          NLP     55yr      Delhi  60000     10

In [ ]:
df['Age']=df['Age'].str.extract('(\d+)')   # string pattern

In [ ]:
df['Exp'] = df['Exp'].str.extract('(\d+)')

In [ ]:
df

    Name       Domain  Age   Location Salary  Exp
0   Mike  Datascience   34     Mumbai   5000    2
1  Teddy      Testing   45  Bangalore  10000    3
2   Umar  Dataanalyst  NaN        NaN  15000    4
3   Jane    Analytics  NaN   Hyderbad  20000  NaN
4  Uttam   Statistics   67        NaN  30000    5
5    Kim          NLP   55      Delhi  60000   10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      object
 3   Location  4 non-null      object
 4   Salary    6 non-null      object
 5   Exp       5 non-null      object
dtypes: object(6)
memory usage: 420.0+ bytes

In [ ]:
df.Exp = df.Exp.astype('float64')
df.Salary = df.Salary.astype('float')
df.Age = df.Age.astype('float')

In [ ]:
df

    Name       Domain   Age   Location   Salary   Exp
0   Mike  Datascience  34.0     Mumbai   5000.0   2.0
1  Teddy      Testing  45.0  Bangalore  10000.0   3.0
2   Umar  Dataanalyst   NaN        NaN  15000.0   4.0
3   Jane    Analytics   NaN   Hyderbad  20000.0   NaN
4  Uttam   Statistics  67.0        NaN  30000.0   5.0
5    Kim          NLP  55.0      Delhi  60000.0  10.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      float64
 3   Location  4 non-null      object
 4   Salary    6 non-null      float64
 5   Exp       5 non-null      float64
dtypes: float64(3), object(3)
memory usage: 420.0+ bytes

# Filling NA values

In [ ]:
df

    Name       Domain   Age   Location   Salary   Exp
0   Mike  Datascience  34.0     Mumbai   5000.0   2.0
1  Teddy      Testing  45.0  Bangalore  10000.0   3.0
2   Umar  Dataanalyst   NaN        NaN  15000.0   4.0
3   Jane    Analytics   NaN   Hyderbad  20000.0   NaN
4  Uttam   Statistics  67.0        NaN  30000.0   5.0
5    Kim          NLP  55.0      Delhi  60000.0  10.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      6 non-null      object
 1   Domain    6 non-null      object
 2   Age       4 non-null      float64
 3   Location  4 non-null      object
 4   Salary    6 non-null      float64
 5   Exp       5 non-null      float64
dtypes: float64(3), object(3)
memory usage: 420.0+ bytes

In [ ]:
import numpy as np

In [ ]:
from ast import match_case
var = df.isna().sum()>0
for i in df.columns:
  # print(i)
  if var[i]:
    print(f"Missing values in {i}:")
    print(df[i])
    print()
    print(df[i].dtype)
    print()
    match df[i].dtype:
      case np.float64:
        df[i].fillna(np.mean(df[i]),inplace=True)
      case np.object_:
        df[i].fillna(df[i].mode()[0],inplace=True)
      case _:
        print("Unknown Datatype Encountered")

Missing values in Age:
0    34.0
1    45.0
2     NaN
3     NaN
4    67.0
5    55.0
Name: Age, dtype: float64

float64

Missing values in Location:
0       Mumbai
1    Bangalore
2          NaN
3     Hyderbad
4          NaN
5        Delhi
Name: Location, dtype: object

object

Missing values in Exp:
0     2.0
1     3.0
2     4.0
3     NaN
4     5.0
5    10.0
Name: Exp, dtype: float64

float64

<ipython-input-19-9f51b2740b39>:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(np.mean(df[i]),inplace=True)
<ipython-input-19-9f51b2740b39>:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[i].fillna(df[i].mode()[0],inplace=True)

In [ ]:
df

    Name       Domain    Age   Location   Salary   Exp
0   Mike  Datascience  34.00     Mumbai   5000.0   2.0
1  Teddy      Testing  45.00  Bangalore  10000.0   3.0
2   Umar  Dataanalyst  50.25  Bangalore  15000.0   4.0
3   Jane    Analytics  50.25   Hyderbad  20000.0   4.8
4  Uttam   Statistics  67.00  Bangalore  30000.0   5.0
5    Kim          NLP  55.00      Delhi  60000.0  10.0